import CardGrid from "@/components/CardGrid";

export const metadata = {
  title: "Music Videos",
  description: "Generated by create next app",
};

const MvsPage = () => {
  return (
    <div className="container mx-auto px-4">
      <h1 className="text-4xl font-bold my-8">Mvs Page</h1>
      <CardGrid />
    </div>
  );
};

export default MvsPage;
