export const metadata = {
  title: "Dance Practices",
  description: "Generated by create next app",
};

const DancePPage = () => {
    return (
      <div className="container mx-auto px-4">
        <h1 className="text-4xl font-bold my-8">DanceP Page</h1>
      </div>
    );
  }

export default DancePPage;  